config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/OSTrails/benchmark-form:
      branch: main
      repo: https://github.com/OSTrails/benchmark-form.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/OSTrails/benchmark-form git:
        commands:
        - /usr/bin/env sh .sqa/script.magenta_cranky_butterfly.sh
        container: qc.acc_wine_peaceful_kangaroo
  QC.Doc:
    repos:
      github.com/OSTrails/benchmark-form find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.turmeric_tranquil_phoenix.sh
        container: qc.doc_gamboge_analytical_llama
      github.com/OSTrails/benchmark-form git:
        commands:
        - /usr/bin/env sh .sqa/script.lagoon_assured_hippopotamus.sh
        container: qc.doc_blush_focused_kirin
      github.com/OSTrails/benchmark-form markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zinnia_upbeat_jellyfish.sh
        container: qc.doc_orange_shy_beaver
  QC.Lic:
    repos:
      github.com/OSTrails/benchmark-form licensee:
        commands:
        - /usr/bin/env sh .sqa/script.carmine_industrious_rattlesnake.sh
        container: qc.lic_sand_bright_raven
  QC.Met:
    repos:
      github.com/OSTrails/benchmark-form cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lagoon_fair_gorilla.sh
        container: qc.met_avocado_vibrant_ostrich
  QC.Sty:
    repos:
      github.com/OSTrails/benchmark-form jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.rust_intuitive_impala.sh
        container: qc.sty_chocolate_forgiving_camel
  QC.Ver:
    repos:
      github.com/OSTrails/benchmark-form get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sapphire_plucky_eel.sh
        container: qc.ver_paprika_dedicated_rattlesnake
timeout: 5400
