config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/OSTrails/benchmark-form:
      branch: main
      repo: https://github.com/OSTrails/benchmark-form.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/OSTrails/benchmark-form git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-celadon-donkey.sh
        container: qc.acc_shaky-olive-wrasse
  QC.Doc:
    repos:
      github.com/OSTrails/benchmark-form find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-goldenrod-crab.sh
        container: qc.doc_beady-tomato-zonkey
      github.com/OSTrails/benchmark-form git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-beige-chinchilla.sh
        container: qc.doc_blurry-gold-gharial
      github.com/OSTrails/benchmark-form markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-tan-flounder.sh
        container: qc.doc_pokey-ultramarine-hyena
  QC.Lic:
    repos:
      github.com/OSTrails/benchmark-form licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-cerise-pig.sh
        container: qc.lic_bumpy-khaki-stingray
  QC.Met:
    repos:
      github.com/OSTrails/benchmark-form cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-azure-tzu.sh
        container: qc.met_sloppy-beige-dragon
  QC.Ver:
    repos:
      github.com/OSTrails/benchmark-form get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-eggplant-penguin.sh
        container: qc.ver_chewy-lemon-bear
timeout: 5400
